### PR TITLE
Target .NET Standard 1.0.

### PR DESCRIPTION
**Pull request by lookatmike**
To start with, this pull request isn't intended to be accepted as-is. It would break for anyone using it in a net40 project and possibly your AppVeyor build as well.

Would you consider adding .NET Standard 1.0 as a target so this library can be used in .NET Core projects? It requires no changes to .cs files to work, but multitargeting certainly adds complexity to project/build management (depending on what AppVeyor supports -- I'm not familiar with it).

I'm also happy to simply keep my netstandard fork updated, just wanted to float the idea of multitargeting.

### CODE REVIEW

**Comment by AndreyTsvetkov** [comment]
Thanks @lookatmike , 
I'll take a look if it is possible to make it work with AppVeyor.

**Comment by lookatmike** [comment]
Thank you @AndreyTsvetkov!

**Comment by Hekku2** [comment]
What is the status for this? (And is there something I can do to help?)

**Comment by vikramadhav** [comment]
I think we are here on standoff, Can i help?

**Comment by Mackiovello** [comment]
If you guys still want a .NET Standard version of this package, I've forked this since the maintainer of this repo no longer seems active: https://github.com/Mackiovello/Mackiovello.Maybe

**Comment by AndreyTsvetkov** [comment]
Well, I'm back and the .NET Standard version is now live and on Nuget.

**Pull request closed without merging**
